version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: router_user
      POSTGRES_PASSWORD: router_password
      POSTGRES_DB: router_db
    ports:
      - "5433:5432"  # External:Internal - changed from 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U router_user -d router_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"  # Also changed from 8000 to 8001 to avoid conflict with your 5000
    environment:
      - DATABASE_URL=postgresql://router_user:router_password@postgres:5432/router_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: